# Server
server.port=${PORT:8080}

# App
spring.application.name=airline-booking-app

# Thymeleaf
spring.thymeleaf.cache=false

# MongoDB
spring.data.mongodb.uri=mongodb+srv://ajeetkumar:ajeetkumar1234@flightintelligence.eprfdwz.mongodb.net/flightdb?appName=FlightIntelligence

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.airline=DEBUG