# Server
server.port=${PORT:8080}

# App
spring.application.name=airline-booking-app

# Thymeleaf
spring.thymeleaf.cache=false

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.airline=DEBUG